import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import EventCalendar from '@/components/view/EventCalendar'
import CourseInformationForm from '@/components/view/CourseInformationForm'
import {EventController} from '@/components/controller/eventController'
import ClearCalButton from '@/components/view/buttons/ClearCalButton'
import {EventModel} from '@/components/model/EventModel'
import FilePickerMBZ from '@/components/view/buttons/FilePickerMBZ'
import DownloadMBZButton from '@/components/view/buttons/DownloadMBZButton'
import ShowSuggestionConfigOverlay from "@/components/view/suggestion/ShowSuggestionConfigOverlay";
import SuggestionButton from "@/components/view/buttons/SuggestionButton";
import SaveAllChangesButton from "@/components/view/buttons/SaveAllChangesButton";
import CancelChangesButton from "@/components/view/buttons/CancelChangesButton";
import ShowOverlay from "@/components/view/buttons/ShowOverlay";
import SuggestionConfig from "@/components/view/suggestion/SuggestionConfig";
import DSLWindow from "@/components/view/DSLWindow";
import ShowEventsByType from '@/components/view/editEvents/ShowEventsByType'
import UI from '@/styles/CoursePlanner.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <EventModel>
            <EventController>
              <EventCalendar />
              <CourseInformationForm />
              <ClearCalButton />
              <div className={UI.flexWrapperTwo}>
                <FilePickerMBZ />
                <DownloadMBZButton />
              </div>

              <ShowOverlay label={"Configurer la suggestion"}>
                <SuggestionConfig />
              </ShowOverlay>

              <SuggestionButton />
              <SaveAllChangesButton />
              <CancelChangesButton />
              <ShowOverlay label={"DSL"}>
                <DSLWindow />
              </ShowOverlay>
              <ShowEventsByType/>
            </EventController>
            
          </EventModel>
        </div>
      </main>
    </>
  )
}
