# -*- coding: utf-8 -*-
import zipfile

# Form implementation generated from reading ui file 'pythonapp3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
import requests
from PyQt6.QtWidgets import QFileDialog
from icalendar import Calendar, Event
from datetime import datetime
import patoolib
import os
import chardet



activities = []
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1255, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 1171, 691))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.activity_end_date = QtWidgets.QLabel(self.tab)
        self.activity_end_date.setGeometry(QtCore.QRect(210, 610, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.activity_end_date.setFont(font)
        self.activity_end_date.setText("")
        self.activity_end_date.setObjectName("activity_end_date")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(60, 300, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Year_label = QtWidgets.QLineEdit(self.tab)
        self.Year_label.setGeometry(QtCore.QRect(200, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.Year_label.setFont(font)
        self.Year_label.setObjectName("Year_label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(60, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(60, 230, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.activity_start_date = QtWidgets.QLabel(self.tab)
        self.activity_start_date.setGeometry(QtCore.QRect(220, 570, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.activity_start_date.setFont(font)
        self.activity_start_date.setText("")
        self.activity_start_date.setObjectName("activity_start_date")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(50, 610, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Sigle_label = QtWidgets.QLineEdit(self.tab)
        self.Sigle_label.setGeometry(QtCore.QRect(200, 110, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.Sigle_label.setFont(font)
        self.Sigle_label.setObjectName("Sigle_label")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 420, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        # Reset button
        self.pushButton_2.clicked.connect(self.reset_btn)

        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(50, 570, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.activity_name = QtWidgets.QLabel(self.tab)
        self.activity_name.setGeometry(QtCore.QRect(140, 530, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.activity_name.setFont(font)
        self.activity_name.setText("")
        self.activity_name.setObjectName("activity_name")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(200, 360, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        # Parsing dates function
        self.pushButton.clicked.connect(self.icalParser)

        self.Groupe_label = QtWidgets.QLineEdit(self.tab)
        self.Groupe_label.setGeometry(QtCore.QRect(200, 170, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.Groupe_label.setFont(font)
        self.Groupe_label.setObjectName("Groupe_label")
        self.listLabel = QtWidgets.QLabel(self.tab)
        self.listLabel.setGeometry(QtCore.QRect(50, 40, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.listLabel.setFont(font)
        self.listLabel.setObjectName("listLabel")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(60, 110, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Session_box = QtWidgets.QComboBox(self.tab)
        self.Session_box.setGeometry(QtCore.QRect(200, 300, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Session_box.setFont(font)
        self.Session_box.setCurrentText("Hiver")
        self.Session_box.setObjectName("Session_box")
        self.Session_box.addItem("")
        self.Session_box.addItem("")
        self.Session_box.addItem("")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(50, 530, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab)
        self.calendarWidget.setGeometry(QtCore.QRect(410, 40, 711, 441))
        self.calendarWidget.setObjectName("calendarWidget")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btnUploadFile = QtWidgets.QPushButton(self.tab_2)
        self.btnUploadFile.setGeometry(QtCore.QRect(550, 90, 121, 41))

        self.btnUploadFile.clicked.connect(self.browsefiles)

        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        self.btnUploadFile.setFont(font)
        self.btnUploadFile.setObjectName("btnUploadFile")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(60, 90, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.fileName = QtWidgets.QLineEdit(self.tab_2)
        self.fileName.setGeometry(QtCore.QRect(260, 89, 261, 41))
        self.fileName.setObjectName("fileName")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1255, 21))
        self.menubar.setObjectName("menubar")
        self.mainMenu = QtWidgets.QMenu(self.menubar)
        self.mainMenu.setObjectName("mainMenu")
        self.ExportMenu = QtWidgets.QMenu(self.menubar)
        self.ExportMenu.setObjectName("ExportMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMBZ = QtGui.QAction(parent=MainWindow)
        self.actionMBZ.setObjectName("actionMBZ")
        self.actionCSV = QtGui.QAction(parent=MainWindow)
        self.actionCSV.setObjectName("actionCSV")
        self.actionNouveau_Cours = QtGui.QAction(parent=MainWindow)
        self.actionNouveau_Cours.setObjectName("actionNouveau_Cours")
        self.actionImporter_MBZ = QtGui.QAction(parent=MainWindow)
        self.actionImporter_MBZ.setObjectName("actionImporter_MBZ")
        self.actionImporter_CSV = QtGui.QAction(parent=MainWindow)
        self.actionImporter_CSV.setObjectName("actionImporter_CSV")
        self.actionSaveChange = QtGui.QAction(parent=MainWindow)
        self.actionSaveChange.setObjectName("actionSaveChange")
        self.actionImporter_fichier_temp = QtGui.QAction(parent=MainWindow)
        self.actionImporter_fichier_temp.setObjectName("actionImporter_fichier_temp")
        self.actionQuitter = QtGui.QAction(parent=MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.mainMenu.addAction(self.actionNouveau_Cours)
        self.mainMenu.addAction(self.actionImporter_MBZ)
        self.mainMenu.addAction(self.actionImporter_CSV)
        self.mainMenu.addAction(self.actionImporter_fichier_temp)
        self.mainMenu.addSeparator()
        self.mainMenu.addAction(self.actionSaveChange)
        self.mainMenu.addAction(self.actionQuitter)
        self.ExportMenu.addAction(self.actionMBZ)
        self.ExportMenu.addAction(self.actionCSV)
        self.menubar.addAction(self.mainMenu.menuAction())
        self.menubar.addAction(self.ExportMenu.menuAction())

        # Connect the calendar to the date function

        self.calendarWidget.selectionChanged.connect(self.grab_date)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def browsefiles(self):
        file_path, _ = QFileDialog.getOpenFileName(MainWindow, "Select file", "All files (*.*)")
        self.fileName.setText(file_path)

        # Extraire le contenu du fichier MBZ
        patoolib.extract_archive(file_path, outdir='/Users/amokranesmail/Downloads/Fichiers MBZ')

        # Parcourir le dossier de sortie et afficher le contenu de chaque fichier
        for root, dirs, files in os.walk('/Users/amokranesmail/Downloads/Fichiers MBZ'):
            for filename in files:
                filepath = os.path.join(root, filename)
                if os.path.exists(filepath):
                    with open(filepath, 'rb') as file:
                        rawdata = file.read()
                        encoding = chardet.detect(rawdata)['encoding']
                        if encoding is None:
                            encoding = 'utf-8'  # logique de secours
                        try:
                            content = rawdata.decode('latin-1')
                        except UnicodeDecodeError:
                            content = rawdata.decode(encoding)
                        print(content)

                        # Ajouter une activité
                        new_activity = """
                            <activity>
                                <moduleid>99999</moduleid>
                                <sectionid>99999</sectionid>
                                <modulename>quiz</modulename>
                                <title>Test modification MBZ</title>
                                <directory>activities/quiz_99999</directory>
                            </activity>
                        """
                        content = content.replace('</module>', new_activity + '</module>')

                        # Écrire le contenu mis à jour dans le fichier
                        with open(filepath, 'wb') as f:
                            f.write(content.encode('utf-8'))

                    # Rezipper le contenu dans un nouveau fichier MBZ
                    with zipfile.ZipFile('nouveau_nom_de_fichier.mbz', 'w') as zip_ref:
                        for root, dirs, files in os.walk('/Users/amokranesmail/Downloads/Fichiers MBZ'):
                            for file in files:
                                zip_ref.write(os.path.join(root, file))

    def icalParser(self):

        global activities

        sigle = self.Sigle_label.text()
        groupe = self.Groupe_label.text()
        annee = self.Year_label.text()
        session = str(self.Session_box.currentText())

        if session == "Hiver":
            session = "1"
        elif session == "Été":
            session = "2"
        elif session == "Automne":
            session = "3"

        url = f"https://portail.etsmtl.ca/ICal/SeancesCours?typeact=C&Sigle={sigle}&Groupe={groupe}&Session={annee}{session}"

        print(url)

        response = requests.get(url)

        cal = Calendar.from_ical(response.content)
        for component in cal.subcomponents:
            if component.name == "VEVENT":
                event = Event.from_ical(component.to_ical())
                activity_name = event['SUMMARY']
                start_date = event['DTSTART'].dt
                end_date = event['DTEND'].dt

                activities.append(activity_name + "," + str(start_date) + "," + str(end_date))
                bg_format = QtGui.QTextCharFormat()
                bg_format.setBackground(QtGui.QBrush(QtGui.QColor(255, 170, 127)))
                self.calendarWidget.setDateTextFormat(start_date.date(), bg_format)
                self.calendarWidget.setToolTip(event['SUMMARY'])

        url2 = f"https://portail.etsmtl.ca/ICal/SeancesCours?typeact=Labo&Sigle={sigle}&Groupe={groupe}&Session={annee}{session}"
        response2 = requests.get(url2)

        # Fetch Lab
        calLab = Calendar.from_ical(response2.content)
        for component in calLab.subcomponents:
            if component.name == "VEVENT":
                event = Event.from_ical(component.to_ical())
                activity_name = event['SUMMARY']
                start_date = event['DTSTART'].dt
                end_date = event['DTEND'].dt

                activities.append(activity_name + "," + str(start_date) + "," + str(end_date))
                bg_format = QtGui.QTextCharFormat()
                bg_format.setBackground(QtGui.QBrush(QtGui.QColor(0, 0, 255)))
                self.calendarWidget.setDateTextFormat(start_date.date(), bg_format)
                self.calendarWidget.setToolTip(event['SUMMARY'])



    def grab_date(self):

        global activities
        dateSelected = str(self.calendarWidget.selectedDate().toPyDate())

        #Set default values

        self.activity_name.setText("Aucune activité")
        self.activity_start_date.setText("")
        self.activity_end_date.setText("")

        for course in activities:
            print(course.split(",")[1])
            print(dateSelected)
            if course.split(",")[1].split(" ")[0] == dateSelected:
                self.activity_name.setText(course.split(",")[0])
                self.activity_start_date.setText(course.split(",")[1])
                self.activity_end_date.setText(course.split(",")[2])



    def reset_btn(self):

        global activities

        bg_format = QtGui.QTextCharFormat()
        bg_format.setBackground(QtGui.QBrush(QtGui.QColor(255, 255, 255)))

        for course in activities:
            date_str = course.split(",")[1].split(" ")[0]
            print(date_str)
            date_obj = datetime.strptime(date_str, '%Y-%m-%d').date()
            print(date_str)
            self.calendarWidget.setDateTextFormat(date_obj, bg_format)

        self.Sigle_label.setText("")
        self.Sigle_label.setText("")
        self.Groupe_label.setText("")
        self.Year_label.setText("")
        #self.Session_box.setItemText("Hiver")
        self.activity_name.setText("")
        self.activity_start_date.setText("")
        self.activity_end_date.setText("")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Session:"))
        self.label_2.setText(_translate("MainWindow", "Groupe:"))
        self.label_3.setText(_translate("MainWindow", "Année:"))
        self.label_7.setText(_translate("MainWindow", "Fin de séance:"))
        self.pushButton_2.setText(_translate("MainWindow", "Reset"))
        self.label_6.setText(_translate("MainWindow", "Début de séance:"))
        self.pushButton.setText(_translate("MainWindow", "Afficher"))
        self.listLabel.setText(_translate("MainWindow", "Liste des activités"))
        self.label.setText(_translate("MainWindow", "Sigle:"))
        self.Session_box.setItemText(0, _translate("MainWindow", "Hiver"))
        self.Session_box.setItemText(1, _translate("MainWindow", "Été"))
        self.Session_box.setItemText(2, _translate("MainWindow", "Automne"))
        self.label_8.setText(_translate("MainWindow", "Activité:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.btnUploadFile.setText(_translate("MainWindow", "Parcourir"))
        self.label_5.setText(_translate("MainWindow", "Importer un fichier:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.mainMenu.setTitle(_translate("MainWindow", "Menu"))
        self.ExportMenu.setTitle(_translate("MainWindow", "Exporter"))
        """
        self.actionMBZ.setText(_translate("MainWindow", "MBZ"))
        self.actionCSV.setText(_translate("MainWindow", "CSV"))
        self.actionNouveau_Cours.setText(_translate("MainWindow", "Nouveau Cours"))
        self.actionImporter_MBZ.setText(_translate("MainWindow", "Importer MBZ"))
        self.actionImporter_CSV.setText(_translate("MainWindow", "Importer CSV"))
        self.actionSaveChange.setText(_translate("MainWindow", "Sauvegarder les changement"))
        self.actionImporter_fichier_temp.setText(_translate("MainWindow", "Importer fichier temp"))
        
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        """


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
